fix: S3/S4之后一键开机进入系统，停留在了密码验证界面
linuxdeepin/dde-session-shell-snipe pull request #128
Opened 2022-08-17 09:01 UTC by chao0903

S3/S4阶段一键开机进入系统失败，会判断上一次登录的类型，导致不能切换到指纹登录

Log: S3/S4之后一键开机进入系统，停留在了密码验证界面
Bug: https://pms.uniontech.com/bug-view-153817.html
Influence: 一键指纹登录插件系统，S3/S4阶段

2022-08-17 11:57 UTC, ssk-wh requested changes

2022-08-17 11:57 UTC, ssk-wh commented on src/session-widgets/sfa_widget.cpp
> +    if(!m_chooseAuthButtonBox->isEnabled() || (m_currentAuthType != AT_Custom && m_model->appType() == AuthCommon::AppType::Login)) {
添加注释说明修改原因，避免后期难以理解

2022-08-18 01:40 UTC, chao0903 commented on src/session-widgets/sfa_widget.cpp
> +    if(!m_chooseAuthButtonBox->isEnabled() || (m_currentAuthType != AT_Custom && m_model->appType() == AuthCommon::AppType::Login)) {
已添加注释，解释修改缘由

2022-08-18 02:22 UTC, wubw1992 approved these changes

2022-08-18 02:26 UTC, shenwenqi3441 commented
/merge

2022-08-18 02:28 UTC, chao0903 commented
merge

2022-08-18 02:32 UTC, chao0903 commented
/merge

2022-08-18 02:52 UTC, ssk-wh approved these changes

2022-08-18 03:34 UTC, chao0903 commented
/merge

2022-08-18 03:34 UTC, merged