chore: adapt license and copyright
linuxdeepin/dde-session-shell-snipe pull request #145
Opened 2022-08-29 07:01 UTC by shao-jun

Modify project to pass the REUSE check

Log: Modify project to pass the REUSE check
Task: https://pms.uniontech.com/task-view-185215.html
Change-Id: Ie746260f467e2b3f18bf5794f5d626dd744eb1ce

2022-08-29 08:43 UTC, BLumia requested changes
一些问题，以及另一些建议。不是所有的都要改，酌情修改。

2022-08-29 08:43 UTC, BLumia commented on .reuse/dep5
> +Files: README.md * README.zh_CN.
```suggestion
Files: README.md README.zh_CN.md
```

这个 `*` 可能影响到 `reuse lint`，去掉后记得 `reuse lint` 重新确认下

2022-08-29 08:43 UTC, BLumia commented on .reuse/dep5
> +Files: *.pro *.prf *.pri *.qrc *CMakeLists.txt *.cmake *.in files/* scripts/* docs/development-guide.md src/lightdm-deepin-greeter/deepin-greeter
```suggestion
Files: *.pro *.prf *.pri *.qrc CMakeLists.txt *.cmake *.in files/* scripts/* docs/development-guide.md src/lightdm-deepin-greeter/deepin-greeter
```

另外 `docs/development-guide.md` 不应该在 project file 里，可以单独写一组 `docs/*` 的

2022-08-29 08:43 UTC, BLumia commented on .reuse/dep5
> +#xml2cpp
```suggestion
# xml2cpp
```

2022-08-29 08:43 UTC, BLumia commented on .reuse/dep5
> +Files: *.qrc
`# Project file` 里有 qrc 了，两边至少一个地方要去掉

2022-08-29 08:43 UTC, BLumia commented on .reuse/dep5
> +License: CC0-1.0
三个可以写到一块，不过这里改不改都行

2022-08-29 08:43 UTC, BLumia commented on .reuse/dep5
> +
没必要这么多空行

2022-08-29 08:43 UTC, BLumia commented on .reuse/dep5
> +Files: *.xml *.toml *.json *conf *.yaml
如果这些文件都是位于共同的目录下的，建议列出路径，这样可以避免新增的文件被错误匹配到这里。

2022-08-29 09:18 UTC, shao-jun commented on .reuse/dep5
> +Files: *.xml *.toml *.json *conf *.yaml
这个只改了xml，其他的文件太分散

2022-08-29 09:27 UTC, BLumia approved these changes

2022-08-29 10:08 UTC, ssk-wh approved these changes

2022-08-29 10:10 UTC, shao-jun commented
/check build-deb

2022-08-30 01:23 UTC, shao-jun commented
/merge

2022-08-30 01:23 UTC, merged