fix: black rectangular background of popup
linuxdeepin/dde-session-shell-snipe pull request #297
Opened 2023-03-10 07:08 UTC by asterwyx

There is black rectangular background under round popup without a window manager when login. Change popup window to a plain widget, draw round rect ourselves.

Log: fix black rectangular background of popup

2023-03-10 07:57 UTC, 18202781743 commented on src/widgets/fakewindowlayer.h
> +    QWidget *content();
const

2023-03-10 07:57 UTC, 18202781743 commented on src/widgets/roundpopupwidget.cpp
> +const int RADIUS = 18;
加上 static

2023-03-10 07:57 UTC, 18202781743 commented on src/widgets/fakewindowlayer.h
> +    Q_PROPERTY(QWidget* content MEMBER m_content READ content WRITE setContent)
member关键字可以去掉

2023-03-10 07:57 UTC, 18202781743 commented on src/session-widgets/sessionbasewindow.cpp
> +    m_fakeWindowLayer->setFixedSize(size());
可以重写m_fakeWindowLayer的 resizeEvent，保证覆盖覆盖富控件

2023-03-10 07:57 UTC, 18202781743 commented on src/session-widgets/sessionbasewindow.cpp
> +    m_fakeWindowLayer->setAutoFillBackground(false);
这个m_fakeWindowLayer默认已经设置，而且应该设置

2023-03-10 07:57 UTC, 18202781743 commented on src/widgets/controlwidget.cpp
> +    baseWindow->showPopup(globalPos, m_roundPopupWidget);
TopWidget，FakeWindowLayer， PopupWidget的关系，是不是应该改成这样，
FakeWindowLayer类似eventfilter的形式使用，
在PopupWidget使用FakeWindowLayer的时候，FakeWindowLayer自己去做这些状态的切换，位置计算，而不是由TopWidget去维护这些，

2023-03-10 07:57 UTC, 18202781743 commented on src/widgets/fakewindowlayer.cpp
> +        m_content->show();
m_content->show()这个，是不是应该移出来，需要判断parentWidget != this么？

2023-03-10 08:55 UTC, asterwyx commented on src/session-widgets/sessionbasewindow.cpp
> +    m_fakeWindowLayer->setFixedSize(size());
已经在父控件的resizeEvent中加入相应的处理逻辑。

2023-03-10 08:55 UTC, asterwyx commented on src/widgets/fakewindowlayer.cpp
> +        m_content->show();
Done.

2023-03-10 09:09 UTC, 18202781743 approved these changes, later dismissed

2023-03-13 03:24 UTC, zccrs requested changes

2023-03-13 03:24 UTC, zccrs commented on src/session-widgets/sessionbasewindow.cpp
> +    while (pw && !pw->inherits(WindowClassName)) {
为什么用 inherits 判断？可以用 qobject_cast 或 dynamic_cast 判断，效率会更好一些。

2023-03-13 03:24 UTC, zccrs commented on src/widgets/controlwidget.cpp
> +        qWarning() << "cannot find a base window";
按照规整的英文语句来写，首字母大写。日志的信息要完备，比如这里应该是`Can't hide the popup widget, not found a base window for" << this;`

不然在追踪log时，只看到一句“cannot find a base window”时完全不能理解是什么错误，除非跟代码对照着看。其他日志的地方类似，就不一一评论了。

2023-03-13 03:24 UTC, zccrs commented on src/widgets/fakewindowlayer.cpp
> +    : QFrame(parent)
应该不需要 QFrame, QWidget可以吗？

2023-03-13 03:24 UTC, zccrs commented on src/widgets/roundpopupwidget.h
> +class RoundPopupWidget : public DBlurEffectWidget
这个变化跟前面的改动是同一件事情吗？如果没有直接的关系，可以分成两个commit

2023-03-13 07:15 UTC, asterwyx commented on src/widgets/fakewindowlayer.cpp
> +    : QFrame(parent)
QWidget也是可以的，用QFrame是为了和其他几部分保持统一。

2023-03-13 08:28 UTC, zccrs commented on src/widgets/fakewindowlayer.cpp
> +    : QFrame(parent)
保持最小化需求原则，使用满足需求的最小元素即可，实际上可以认为其它代码中使用 QFrame 是一种滥用，新代码中不用跟随错误的行为。

2023-03-13 09:38 UTC, asterwyx commented on src/widgets/roundpopupwidget.h
> +class RoundPopupWidget : public DBlurEffectWidget
已拆分成两次提交。

2023-03-14 05:26 UTC, zccrs submitted a review, later dismissed

2023-03-14 05:28 UTC, 18202781743 approved these changes

2023-03-14 07:18 UTC, merged