fix: second click of network won't close network panel
linuxdeepin/dde-session-shell-snipe pull request #298
Opened 2023-03-16 09:53 UTC by asterwyx

Network panel used to be controlled by dss-network-plugin, click
button simply show the panel. Let panel controlled by dde-session-shell.
dss-network-plugin just return its content. Use a fake popup instead of
a popup window.

2023-03-20 01:33 UTC, 18202781743 commented on src/global_util/modules_loader.cpp
> +    addModulePath(ModulesDir);
是不是应该优先找localDir的module

2023-03-20 01:33 UTC, 18202781743 commented on src/app/dde-lock.cpp
> +        modulesLoader->clearModulePath();
为什么需要先clear,应该有个添加的优先级就可以了，或者提供set接口，而不是两个接口组合起来用

2023-03-20 02:37 UTC, zccrs requested changes

2023-03-20 02:37 UTC, zccrs commented on src/app/dde-lock.cpp
> +    QCommandLineOption modulePath("p", "paths to load modules in debug mode, separated by semicolon.", "paths", QString());
段落开头首字母大写

2023-03-20 08:31 UTC, 18202781743 commented
+1

2023-03-21 03:59 UTC, BLumia commented on src/widgets/controlwidget.h
> +    FloatingButton(const QIcon& icon, const QString &text = QString(), QWidget *parent = nullptr)
cppcheck: Class 'FloatingButton' has a constructor with 1 argument that is not explicit. Such constructors should in general be explicit for type safety reasons. Using the explicit keyword in the constructor means some mistakes when using the class can be avoided.

2023-03-21 06:27 UTC, asterwyx commented on src/widgets/controlwidget.h
> +    FloatingButton(const QIcon& icon, const QString &text = QString(), QWidget *parent = nullptr)
我这次的提交只改了拼写的问题，这种错误是不是应该分一次提交出来。

2023-03-21 06:40 UTC, BLumia commented on src/widgets/controlwidget.h
> +    FloatingButton(const QIcon& icon, const QString &text = QString(), QWidget *parent = nullptr)
可以，那就不在此 PR 处理也行

2023-03-21 06:41 UTC, BLumia approved these changes, later dismissed

2023-03-21 06:52 UTC, asterwyx commented
网络插件的通知功能异常，需要追加提交。

2023-03-22 06:53 UTC, zccrs submitted a review, later dismissed

2023-03-22 06:53 UTC, zccrs commented
/+1

2023-03-24 01:20 UTC, 18202781743 commented on src/app/dde-lock.cpp
> +    DLogManager::registerFileAppender();
这个file appender会根据applicationName来组织log的路径，这样改就读不到正确的了，并且会提前构造qapplication,

2023-03-26 10:55 UTC, BLumia approved these changes

2023-03-28 01:57 UTC, merged