fix: session name editable
linuxdeepin/dde-session-shell-snipe pull request #335
Opened 2023-08-23 05:46 UTC by asterwyx

Session should not be editable, remove EditRole from item flags.

Log: fix session name editable

2023-08-23 05:52 UTC, asterwyx commented
/integrate

2023-08-23 06:19 UTC, dengbo11 approved these changes, later dismissed

2023-08-23 07:18 UTC, BLumia approved these changes, later dismissed

2023-08-25 01:23 UTC, justforlxz requested changes

2023-08-25 01:23 UTC, justforlxz commented on src/widgets/sessionpopupwidget.cpp
> +    item->setFlags(item->flags() & ~Qt::EditRole);
`QStandardItem::setEditable`

用这个禁用掉就可以了。

2023-08-25 05:37 UTC, justforlxz approved these changes

2023-08-25 07:00 UTC, asterwyx commented
/merge

2023-08-25 07:00 UTC, merged