feat: no password unlock
linuxdeepin/dde-session-shell-snipe pull request #341
Opened 2023-10-09 06:23 UTC by Decodetalkers

Log:

2023-10-09 06:33 UTC, Decodetalkers commented
https://github.com/linuxdeepin/dde-session-shell/pull/239/files 

原始的pr,

2023-10-10 05:11 UTC, Decodetalkers commented
/check obs

2023-10-10 05:18 UTC, asterwyx requested changes

2023-10-10 05:18 UTC, asterwyx commented on .gitignore
> +.cache
这个文件的更改单独分commit

2023-10-10 05:20 UTC, Decodetalkers commented on .gitignore
> +.cache
好了

2023-10-10 05:27 UTC, asterwyx reviewed
代码的效果和产品预期一致吗，如果这样改，锁屏应该就没有作用了

2023-10-10 05:27 UTC, Decodetalkers commented
> 代码的效果和产品预期一致吗，如果这样改，锁屏应该就没有作用了

当是无密码登陆时候锁屏不需要密码这样

2023-10-10 05:28 UTC, asterwyx approved these changes

2023-10-10 05:29 UTC, asterwyx commented
OBS仓库自己有问题，等构建过了就可以合了

2023-10-10 05:37 UTC, Decodetalkers commented
/integrate

2023-10-13 03:20 UTC, Decodetalkers commented
/retest

2023-10-13 03:20 UTC, Decodetalkers commented
/check obs

2023-10-13 03:24 UTC, merged